apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hudocafe
  namespace: argocd
spec:
  description: "Hudocafe DevOps project"

  sourceRepos:
    - "https://github.com/YOUR_USERNAME/DevOps-project"  # ← Change!

  destinations:
    - namespace: production
      server:    https://kubernetes.default.svc
    - namespace: argocd
      server:    https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding

  namespaceResourceWhitelist:
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: PersistentVolumeClaim
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "autoscaling"
      kind: HorizontalPodAutoscaler
